name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        board: ["ESP8266", "ESP32", "ESP32-C3"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          pip install --upgrade platformio

      - name: Compile ${{ matrix.board }}
        run: |
          pio run -e ${{ matrix.board }}

